spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gangnaenglog@gmail.com
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret:
  access-token-expire-time: 1800000
  refresh-token-expire-time: 1209600000